security:
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_BOARD]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: /
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            switch_user:  { role: ROLE_ADMIN }

    access_control:
        - { path: ^/register,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/homepage,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,     role: ROLE_USER }
        - { path: ^/api/doc,   role: ROLE_SUPER_ADMIN }
        - { path: ^/_console,   role: ROLE_SUPER_ADMIN }
