services:
    main.notification.service:
        class: MainBundle\Service\NotificationService
        arguments:
            - "@main.notification.manager"
            - "@main.section.fetcher"
            - "@main.notification.creator"
            - "@main.notification.helper"
            - "@main.regid.adapter"
            - "@security.authorization_checker"

    main.guide.service:
       class: MainBundle\Service\GuideService
       arguments:
           - "@main.guide.fetcher"
           - "@main.guide.manager"

    main.country.service:
        class: MainBundle\Service\CountryService
        arguments:
            - "@main.country.fetcher"

    main.section.service:
        class: MainBundle\Service\SectionService
        arguments:
            - "@main.section.fetcher"
            - "@main.section.manager"

    main.import_countries.service:
        class: MainBundle\Service\ImportCountriesService
        arguments:
            - "@main.import_countries.reader"
            - "@main.country.manager"
            - "@main.country.fetcher"
            - "@event_dispatcher"

    main.import_sections.service:
        class: MainBundle\Service\ImportSectionsService
        arguments:
            - "@main.import_sections.reader"
            - "@main.country.manager"
            - "@main.country.fetcher"
            - "@main.section.manager"
            - "@event_dispatcher"

    main.category.service:
        class: MainBundle\Service\CategoryService
        arguments:
            - "@main.category.manager"
            - "@main.category.adapter"
